image: node:16.15

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm i -g create-docusaurus
    - npm i
    - npm run build
    - mv ./build ./public

  artifacts:
    paths:
      - public/
